
CondaError: Run 'conda init' before 'conda deactivate'

2024-09-26 11:19:04,974 - INFO - Starting the main function
2024-09-26 11:19:05,041 - INFO - Parameters loaded successfully.
2024-09-26 11:19:05,041 - ERROR - Failed to load gaze data from /gpfs/milgram/project/chang/pg496/data_dir/social_gaze/intermediates/nan_removed_gaze_data_dict.pkl: get_nan_removed_gaze_data_dict() missing 1 required positional argument: 'missing_data_file_path'
